<%@ page language="java" contentType="text/html; charset=UTF-8"%>
<%@ page pageEncoding="UTF-8"%>
<%@ page import="java.util.*,dao.*,model.*"%>
<META NAME="KeyWords" CONTENT="團購訂餐'團購美食'團購網">
<META NAME="Description" CONTENT="這是一個團購美食的好地方!!">
<META name="viewport"
	content="width=device-width, initial-scale=1, maximum-scale=1">
<!--fonts-->
<link
	href='http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700,800'
	rel='stylesheet' type='text/css'>
<!--//fonts-->
<!--theme-style-->
<link href="css/jquery-ui.min.css" rel="stylesheet" type="text/css"
	media="all" />
<link href="css/bootstrap.min.css" rel="stylesheet" type="text/css"
	media="all" />
<link href="css/bootstrap-theme.css" rel="stylesheet" type="text/css"
	media="all" />
<link href="css/etalage.css" rel="stylesheet" type="text/css"
	media="all" />
<link href='css/jqcloud.min.css' rel='stylesheet' type='text/css'>
<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
<link href="http://cdnjs.cloudflare.com/ajax/libs/alertify.js/0.3.10/alertify.core.css" rel="stylesheet">  
<link href="http://cdnjs.cloudflare.com/ajax/libs/alertify.js/0.3.10/alertify.default.css" rel="stylesheet">  
<!--//theme-style-->
<!--script-->
<script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
<script src="js/jquery-ui.min.js" ></script>
<script src="js/jquery.etalage.min.js" ></script>
<script src="js/jqcloud.min.js" ></script>
<script src="http://malsup.github.io/jquery.form.js"></script>
<script src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js"></script>
<script src="http://cdn.jsdelivr.net/jquery.validation/1.15.0/additional-methods.min.js"></script>
<script src="http://cdnjs.cloudflare.com/ajax/libs/alertify.js/0.3.10/alertify.min.js"></script>  
<script src="js/messages_zh_TW.js"></script>
<script src="js/myjs.js" ></script>
<script type="application/x-javascript">
	 addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } 
</script>
<!--//script-->